/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddressCreateDto,
  AddressResponseDto,
  BusinessCustomerCreateDto,
  BusinessCustomerResponseDto,
  BusinessCustomerUpdateDto,
  CustomerContactCreateDto,
  CustomerContactResponseDto,
} from '../models/index';
import {
    AddressCreateDtoFromJSON,
    AddressCreateDtoToJSON,
    AddressResponseDtoFromJSON,
    AddressResponseDtoToJSON,
    BusinessCustomerCreateDtoFromJSON,
    BusinessCustomerCreateDtoToJSON,
    BusinessCustomerResponseDtoFromJSON,
    BusinessCustomerResponseDtoToJSON,
    BusinessCustomerUpdateDtoFromJSON,
    BusinessCustomerUpdateDtoToJSON,
    CustomerContactCreateDtoFromJSON,
    CustomerContactCreateDtoToJSON,
    CustomerContactResponseDtoFromJSON,
    CustomerContactResponseDtoToJSON,
} from '../models/index';

export interface CreateBusinessCustomerRequest {
    businessCustomerCreateDto: BusinessCustomerCreateDto;
}

export interface CreateContactForBusinessRequest {
    businessId: number;
    customerContactCreateDto: CustomerContactCreateDto;
}

export interface CreateOperationalAddressForBusinessRequest {
    businessId: number;
    addressCreateDto: AddressCreateDto;
}

export interface DeleteContactRequest {
    businessId: number;
    contactId: number;
}

export interface DeleteOperationalAddressRequest {
    businessId: number;
    operationalAddressId: number;
}

export interface GetBusinessCustomerByIdRequest {
    id: number;
}

export interface UpdateBusinessCustomerRequest {
    id: number;
    businessCustomerUpdateDto: BusinessCustomerUpdateDto;
}

/**
 * 
 */
export class CustomerManagementBusinessApi extends runtime.BaseAPI {

    /**
     * Create a new business customer
     */
    async createBusinessCustomerRaw(requestParameters: CreateBusinessCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessCustomerResponseDto>> {
        if (requestParameters['businessCustomerCreateDto'] == null) {
            throw new runtime.RequiredError(
                'businessCustomerCreateDto',
                'Required parameter "businessCustomerCreateDto" was null or undefined when calling createBusinessCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/business`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BusinessCustomerCreateDtoToJSON(requestParameters['businessCustomerCreateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessCustomerResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a new business customer
     */
    async createBusinessCustomer(requestParameters: CreateBusinessCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessCustomerResponseDto> {
        const response = await this.createBusinessCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new contact for a business customer
     */
    async createContactForBusinessRaw(requestParameters: CreateContactForBusinessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerContactResponseDto>> {
        if (requestParameters['businessId'] == null) {
            throw new runtime.RequiredError(
                'businessId',
                'Required parameter "businessId" was null or undefined when calling createContactForBusiness().'
            );
        }

        if (requestParameters['customerContactCreateDto'] == null) {
            throw new runtime.RequiredError(
                'customerContactCreateDto',
                'Required parameter "customerContactCreateDto" was null or undefined when calling createContactForBusiness().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/business/{businessId}/contacts`;
        urlPath = urlPath.replace(`{${"businessId"}}`, encodeURIComponent(String(requestParameters['businessId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerContactCreateDtoToJSON(requestParameters['customerContactCreateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerContactResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a new contact for a business customer
     */
    async createContactForBusiness(requestParameters: CreateContactForBusinessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerContactResponseDto> {
        const response = await this.createContactForBusinessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new operational address for a business customer
     */
    async createOperationalAddressForBusinessRaw(requestParameters: CreateOperationalAddressForBusinessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddressResponseDto>> {
        if (requestParameters['businessId'] == null) {
            throw new runtime.RequiredError(
                'businessId',
                'Required parameter "businessId" was null or undefined when calling createOperationalAddressForBusiness().'
            );
        }

        if (requestParameters['addressCreateDto'] == null) {
            throw new runtime.RequiredError(
                'addressCreateDto',
                'Required parameter "addressCreateDto" was null or undefined when calling createOperationalAddressForBusiness().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/business/{businessId}/operational-addresses`;
        urlPath = urlPath.replace(`{${"businessId"}}`, encodeURIComponent(String(requestParameters['businessId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddressCreateDtoToJSON(requestParameters['addressCreateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddressResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a new operational address for a business customer
     */
    async createOperationalAddressForBusiness(requestParameters: CreateOperationalAddressForBusinessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddressResponseDto> {
        const response = await this.createOperationalAddressForBusinessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a contact from a business customer
     */
    async deleteContactRaw(requestParameters: DeleteContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['businessId'] == null) {
            throw new runtime.RequiredError(
                'businessId',
                'Required parameter "businessId" was null or undefined when calling deleteContact().'
            );
        }

        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling deleteContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/business/{businessId}/contacts/{contactId}`;
        urlPath = urlPath.replace(`{${"businessId"}}`, encodeURIComponent(String(requestParameters['businessId'])));
        urlPath = urlPath.replace(`{${"contactId"}}`, encodeURIComponent(String(requestParameters['contactId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a contact from a business customer
     */
    async deleteContact(requestParameters: DeleteContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteContactRaw(requestParameters, initOverrides);
    }

    /**
     * Delete an operational address from a business customer
     */
    async deleteOperationalAddressRaw(requestParameters: DeleteOperationalAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['businessId'] == null) {
            throw new runtime.RequiredError(
                'businessId',
                'Required parameter "businessId" was null or undefined when calling deleteOperationalAddress().'
            );
        }

        if (requestParameters['operationalAddressId'] == null) {
            throw new runtime.RequiredError(
                'operationalAddressId',
                'Required parameter "operationalAddressId" was null or undefined when calling deleteOperationalAddress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/business/{businessId}/operational-addresses/{operationalAddressId}`;
        urlPath = urlPath.replace(`{${"businessId"}}`, encodeURIComponent(String(requestParameters['businessId'])));
        urlPath = urlPath.replace(`{${"operationalAddressId"}}`, encodeURIComponent(String(requestParameters['operationalAddressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an operational address from a business customer
     */
    async deleteOperationalAddress(requestParameters: DeleteOperationalAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOperationalAddressRaw(requestParameters, initOverrides);
    }

    /**
     * Get a business customer by ID
     */
    async getBusinessCustomerByIdRaw(requestParameters: GetBusinessCustomerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessCustomerResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBusinessCustomerById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/business/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessCustomerResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a business customer by ID
     */
    async getBusinessCustomerById(requestParameters: GetBusinessCustomerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessCustomerResponseDto> {
        const response = await this.getBusinessCustomerByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a business customer\'s main details
     */
    async updateBusinessCustomerRaw(requestParameters: UpdateBusinessCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessCustomerResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateBusinessCustomer().'
            );
        }

        if (requestParameters['businessCustomerUpdateDto'] == null) {
            throw new runtime.RequiredError(
                'businessCustomerUpdateDto',
                'Required parameter "businessCustomerUpdateDto" was null or undefined when calling updateBusinessCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/business/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BusinessCustomerUpdateDtoToJSON(requestParameters['businessCustomerUpdateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessCustomerResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update a business customer\'s main details
     */
    async updateBusinessCustomer(requestParameters: UpdateBusinessCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessCustomerResponseDto> {
        const response = await this.updateBusinessCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
