/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IndividualCustomerCreateDto,
  IndividualCustomerResponseDto,
  IndividualCustomerUpdateDto,
} from '../models/index';
import {
    IndividualCustomerCreateDtoFromJSON,
    IndividualCustomerCreateDtoToJSON,
    IndividualCustomerResponseDtoFromJSON,
    IndividualCustomerResponseDtoToJSON,
    IndividualCustomerUpdateDtoFromJSON,
    IndividualCustomerUpdateDtoToJSON,
} from '../models/index';

export interface CreatePrivateCustomerRequest {
    individualCustomerCreateDto: IndividualCustomerCreateDto;
}

export interface GetPrivateCustomerByIdRequest {
    id: number;
}

export interface UpdatePrivateCustomerRequest {
    id: number;
    individualCustomerUpdateDto: IndividualCustomerUpdateDto;
}

/**
 * 
 */
export class CustomerManagementIndividualApi extends runtime.BaseAPI {

    /**
     * Create a new individual customer
     */
    async createPrivateCustomerRaw(requestParameters: CreatePrivateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndividualCustomerResponseDto>> {
        if (requestParameters['individualCustomerCreateDto'] == null) {
            throw new runtime.RequiredError(
                'individualCustomerCreateDto',
                'Required parameter "individualCustomerCreateDto" was null or undefined when calling createPrivateCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/individual`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IndividualCustomerCreateDtoToJSON(requestParameters['individualCustomerCreateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndividualCustomerResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a new individual customer
     */
    async createPrivateCustomer(requestParameters: CreatePrivateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndividualCustomerResponseDto> {
        const response = await this.createPrivateCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a individual customer by ID
     */
    async getPrivateCustomerByIdRaw(requestParameters: GetPrivateCustomerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndividualCustomerResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPrivateCustomerById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/individual/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndividualCustomerResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a individual customer by ID
     */
    async getPrivateCustomerById(requestParameters: GetPrivateCustomerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndividualCustomerResponseDto> {
        const response = await this.getPrivateCustomerByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a individual customer\'s main details
     */
    async updatePrivateCustomerRaw(requestParameters: UpdatePrivateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndividualCustomerResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePrivateCustomer().'
            );
        }

        if (requestParameters['individualCustomerUpdateDto'] == null) {
            throw new runtime.RequiredError(
                'individualCustomerUpdateDto',
                'Required parameter "individualCustomerUpdateDto" was null or undefined when calling updatePrivateCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/customers/individual/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IndividualCustomerUpdateDtoToJSON(requestParameters['individualCustomerUpdateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndividualCustomerResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update a individual customer\'s main details
     */
    async updatePrivateCustomer(requestParameters: UpdatePrivateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndividualCustomerResponseDto> {
        const response = await this.updatePrivateCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
