/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressResponseDto
 */
export interface AddressResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AddressResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AddressResponseDto
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponseDto
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponseDto
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponseDto
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponseDto
     */
    province?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponseDto
     */
    country?: string;
}

/**
 * Check if a given object implements the AddressResponseDto interface.
 */
export function instanceOfAddressResponseDto(value: object): value is AddressResponseDto {
    return true;
}

export function AddressResponseDtoFromJSON(json: any): AddressResponseDto {
    return AddressResponseDtoFromJSONTyped(json, false);
}

export function AddressResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'street': json['street'] == null ? undefined : json['street'],
        'number': json['number'] == null ? undefined : json['number'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'city': json['city'] == null ? undefined : json['city'],
        'province': json['province'] == null ? undefined : json['province'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function AddressResponseDtoToJSON(json: any): AddressResponseDto {
    return AddressResponseDtoToJSONTyped(json, false);
}

export function AddressResponseDtoToJSONTyped(value?: AddressResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'street': value['street'],
        'number': value['number'],
        'postalCode': value['postalCode'],
        'city': value['city'],
        'province': value['province'],
        'country': value['country'],
    };
}

