/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressUpdateDto
 */
export interface AddressUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDto
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDto
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDto
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDto
     */
    province?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDto
     */
    country: string;
}

/**
 * Check if a given object implements the AddressUpdateDto interface.
 */
export function instanceOfAddressUpdateDto(value: object): value is AddressUpdateDto {
    if (!('street' in value) || value['street'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function AddressUpdateDtoFromJSON(json: any): AddressUpdateDto {
    return AddressUpdateDtoFromJSONTyped(json, false);
}

export function AddressUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'street': json['street'],
        'number': json['number'],
        'postalCode': json['postalCode'],
        'city': json['city'],
        'province': json['province'] == null ? undefined : json['province'],
        'country': json['country'],
    };
}

export function AddressUpdateDtoToJSON(json: any): AddressUpdateDto {
    return AddressUpdateDtoToJSONTyped(json, false);
}

export function AddressUpdateDtoToJSONTyped(value?: AddressUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'number': value['number'],
        'postalCode': value['postalCode'],
        'city': value['city'],
        'province': value['province'],
        'country': value['country'],
    };
}

