/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressResponseDto } from './AddressResponseDto';
import {
    AddressResponseDtoFromJSON,
    AddressResponseDtoFromJSONTyped,
    AddressResponseDtoToJSON,
    AddressResponseDtoToJSONTyped,
} from './AddressResponseDto';
import type { CustomerContactResponseDto } from './CustomerContactResponseDto';
import {
    CustomerContactResponseDtoFromJSON,
    CustomerContactResponseDtoFromJSONTyped,
    CustomerContactResponseDtoToJSON,
    CustomerContactResponseDtoToJSONTyped,
} from './CustomerContactResponseDto';

/**
 * 
 * @export
 * @interface BusinessCustomerResponseDto
 */
export interface BusinessCustomerResponseDto {
    /**
     * 
     * @type {number}
     * @memberof BusinessCustomerResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerResponseDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerResponseDto
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerResponseDto
     */
    customerType?: BusinessCustomerResponseDtoCustomerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerResponseDto
     */
    companyName?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerResponseDto
     */
    vatNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerResponseDto
     */
    fiscalCode?: string;
    /**
     * 
     * @type {AddressResponseDto}
     * @memberof BusinessCustomerResponseDto
     */
    legalAddress?: AddressResponseDto;
    /**
     * 
     * @type {AddressResponseDto}
     * @memberof BusinessCustomerResponseDto
     */
    billingAddress?: AddressResponseDto;
    /**
     * 
     * @type {Set<AddressResponseDto>}
     * @memberof BusinessCustomerResponseDto
     */
    operationalAddresses?: Set<AddressResponseDto>;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerResponseDto
     */
    sdiCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerResponseDto
     */
    pecEmail?: string;
    /**
     * 
     * @type {Set<CustomerContactResponseDto>}
     * @memberof BusinessCustomerResponseDto
     */
    contacts?: Set<CustomerContactResponseDto>;
}


/**
 * @export
 */
export const BusinessCustomerResponseDtoCustomerTypeEnum = {
    Individual: 'INDIVIDUAL',
    Business: 'BUSINESS'
} as const;
export type BusinessCustomerResponseDtoCustomerTypeEnum = typeof BusinessCustomerResponseDtoCustomerTypeEnum[keyof typeof BusinessCustomerResponseDtoCustomerTypeEnum];


/**
 * Check if a given object implements the BusinessCustomerResponseDto interface.
 */
export function instanceOfBusinessCustomerResponseDto(value: object): value is BusinessCustomerResponseDto {
    return true;
}

export function BusinessCustomerResponseDtoFromJSON(json: any): BusinessCustomerResponseDto {
    return BusinessCustomerResponseDtoFromJSONTyped(json, false);
}

export function BusinessCustomerResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessCustomerResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'customerType': json['customerType'] == null ? undefined : json['customerType'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'vatNumber': json['vatNumber'] == null ? undefined : json['vatNumber'],
        'fiscalCode': json['fiscalCode'] == null ? undefined : json['fiscalCode'],
        'legalAddress': json['legalAddress'] == null ? undefined : AddressResponseDtoFromJSON(json['legalAddress']),
        'billingAddress': json['billingAddress'] == null ? undefined : AddressResponseDtoFromJSON(json['billingAddress']),
        'operationalAddresses': json['operationalAddresses'] == null ? undefined : (new Set((json['operationalAddresses'] as Array<any>).map(AddressResponseDtoFromJSON))),
        'sdiCode': json['sdiCode'] == null ? undefined : json['sdiCode'],
        'pecEmail': json['pecEmail'] == null ? undefined : json['pecEmail'],
        'contacts': json['contacts'] == null ? undefined : (new Set((json['contacts'] as Array<any>).map(CustomerContactResponseDtoFromJSON))),
    };
}

export function BusinessCustomerResponseDtoToJSON(json: any): BusinessCustomerResponseDto {
    return BusinessCustomerResponseDtoToJSONTyped(json, false);
}

export function BusinessCustomerResponseDtoToJSONTyped(value?: BusinessCustomerResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'customerType': value['customerType'],
        'companyName': value['companyName'],
        'vatNumber': value['vatNumber'],
        'fiscalCode': value['fiscalCode'],
        'legalAddress': AddressResponseDtoToJSON(value['legalAddress']),
        'billingAddress': AddressResponseDtoToJSON(value['billingAddress']),
        'operationalAddresses': value['operationalAddresses'] == null ? undefined : (Array.from(value['operationalAddresses'] as Set<any>).map(AddressResponseDtoToJSON)),
        'sdiCode': value['sdiCode'],
        'pecEmail': value['pecEmail'],
        'contacts': value['contacts'] == null ? undefined : (Array.from(value['contacts'] as Set<any>).map(CustomerContactResponseDtoToJSON)),
    };
}

