/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressUpdateDto } from './AddressUpdateDto';
import {
    AddressUpdateDtoFromJSON,
    AddressUpdateDtoFromJSONTyped,
    AddressUpdateDtoToJSON,
    AddressUpdateDtoToJSONTyped,
} from './AddressUpdateDto';

/**
 * 
 * @export
 * @interface BusinessCustomerUpdateDto
 */
export interface BusinessCustomerUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerUpdateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerUpdateDto
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerUpdateDto
     */
    companyName: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerUpdateDto
     */
    vatNumber: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerUpdateDto
     */
    fiscalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerUpdateDto
     */
    sdiCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerUpdateDto
     */
    pecEmail?: string;
    /**
     * 
     * @type {AddressUpdateDto}
     * @memberof BusinessCustomerUpdateDto
     */
    legalAddress: AddressUpdateDto;
    /**
     * 
     * @type {AddressUpdateDto}
     * @memberof BusinessCustomerUpdateDto
     */
    billingAddress: AddressUpdateDto;
}

/**
 * Check if a given object implements the BusinessCustomerUpdateDto interface.
 */
export function instanceOfBusinessCustomerUpdateDto(value: object): value is BusinessCustomerUpdateDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('companyName' in value) || value['companyName'] === undefined) return false;
    if (!('vatNumber' in value) || value['vatNumber'] === undefined) return false;
    if (!('legalAddress' in value) || value['legalAddress'] === undefined) return false;
    if (!('billingAddress' in value) || value['billingAddress'] === undefined) return false;
    return true;
}

export function BusinessCustomerUpdateDtoFromJSON(json: any): BusinessCustomerUpdateDto {
    return BusinessCustomerUpdateDtoFromJSONTyped(json, false);
}

export function BusinessCustomerUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessCustomerUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'companyName': json['companyName'],
        'vatNumber': json['vatNumber'],
        'fiscalCode': json['fiscalCode'] == null ? undefined : json['fiscalCode'],
        'sdiCode': json['sdiCode'] == null ? undefined : json['sdiCode'],
        'pecEmail': json['pecEmail'] == null ? undefined : json['pecEmail'],
        'legalAddress': AddressUpdateDtoFromJSON(json['legalAddress']),
        'billingAddress': AddressUpdateDtoFromJSON(json['billingAddress']),
    };
}

export function BusinessCustomerUpdateDtoToJSON(json: any): BusinessCustomerUpdateDto {
    return BusinessCustomerUpdateDtoToJSONTyped(json, false);
}

export function BusinessCustomerUpdateDtoToJSONTyped(value?: BusinessCustomerUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'companyName': value['companyName'],
        'vatNumber': value['vatNumber'],
        'fiscalCode': value['fiscalCode'],
        'sdiCode': value['sdiCode'],
        'pecEmail': value['pecEmail'],
        'legalAddress': AddressUpdateDtoToJSON(value['legalAddress']),
        'billingAddress': AddressUpdateDtoToJSON(value['billingAddress']),
    };
}

