/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressCreateDto } from './AddressCreateDto';
import {
    AddressCreateDtoFromJSON,
    AddressCreateDtoFromJSONTyped,
    AddressCreateDtoToJSON,
    AddressCreateDtoToJSONTyped,
} from './AddressCreateDto';

/**
 * 
 * @export
 * @interface BusinessCustomerCreateDto
 */
export interface BusinessCustomerCreateDto {
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerCreateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerCreateDto
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerCreateDto
     */
    companyName: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerCreateDto
     */
    vatNumber: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerCreateDto
     */
    fiscalCode?: string;
    /**
     * 
     * @type {AddressCreateDto}
     * @memberof BusinessCustomerCreateDto
     */
    legalAddress: AddressCreateDto;
    /**
     * 
     * @type {AddressCreateDto}
     * @memberof BusinessCustomerCreateDto
     */
    billingAddress: AddressCreateDto;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerCreateDto
     */
    sdiCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessCustomerCreateDto
     */
    pecEmail?: string;
}

/**
 * Check if a given object implements the BusinessCustomerCreateDto interface.
 */
export function instanceOfBusinessCustomerCreateDto(value: object): value is BusinessCustomerCreateDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('companyName' in value) || value['companyName'] === undefined) return false;
    if (!('vatNumber' in value) || value['vatNumber'] === undefined) return false;
    if (!('legalAddress' in value) || value['legalAddress'] === undefined) return false;
    if (!('billingAddress' in value) || value['billingAddress'] === undefined) return false;
    return true;
}

export function BusinessCustomerCreateDtoFromJSON(json: any): BusinessCustomerCreateDto {
    return BusinessCustomerCreateDtoFromJSONTyped(json, false);
}

export function BusinessCustomerCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessCustomerCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'companyName': json['companyName'],
        'vatNumber': json['vatNumber'],
        'fiscalCode': json['fiscalCode'] == null ? undefined : json['fiscalCode'],
        'legalAddress': AddressCreateDtoFromJSON(json['legalAddress']),
        'billingAddress': AddressCreateDtoFromJSON(json['billingAddress']),
        'sdiCode': json['sdiCode'] == null ? undefined : json['sdiCode'],
        'pecEmail': json['pecEmail'] == null ? undefined : json['pecEmail'],
    };
}

export function BusinessCustomerCreateDtoToJSON(json: any): BusinessCustomerCreateDto {
    return BusinessCustomerCreateDtoToJSONTyped(json, false);
}

export function BusinessCustomerCreateDtoToJSONTyped(value?: BusinessCustomerCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'companyName': value['companyName'],
        'vatNumber': value['vatNumber'],
        'fiscalCode': value['fiscalCode'],
        'legalAddress': AddressCreateDtoToJSON(value['legalAddress']),
        'billingAddress': AddressCreateDtoToJSON(value['billingAddress']),
        'sdiCode': value['sdiCode'],
        'pecEmail': value['pecEmail'],
    };
}

