/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerResponseDto
 */
export interface CustomerResponseDto {
    /**
     * 
     * @type {number}
     * @memberof CustomerResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseDto
     */
    customerType?: CustomerResponseDtoCustomerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseDto
     */
    displayName?: string;
}


/**
 * @export
 */
export const CustomerResponseDtoCustomerTypeEnum = {
    Individual: 'INDIVIDUAL',
    Business: 'BUSINESS'
} as const;
export type CustomerResponseDtoCustomerTypeEnum = typeof CustomerResponseDtoCustomerTypeEnum[keyof typeof CustomerResponseDtoCustomerTypeEnum];


/**
 * Check if a given object implements the CustomerResponseDto interface.
 */
export function instanceOfCustomerResponseDto(value: object): value is CustomerResponseDto {
    return true;
}

export function CustomerResponseDtoFromJSON(json: any): CustomerResponseDto {
    return CustomerResponseDtoFromJSONTyped(json, false);
}

export function CustomerResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'customerType': json['customerType'] == null ? undefined : json['customerType'],
        'email': json['email'] == null ? undefined : json['email'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
    };
}

export function CustomerResponseDtoToJSON(json: any): CustomerResponseDto {
    return CustomerResponseDtoToJSONTyped(json, false);
}

export function CustomerResponseDtoToJSONTyped(value?: CustomerResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerType': value['customerType'],
        'email': value['email'],
        'displayName': value['displayName'],
    };
}

