/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerContactResponseDto
 */
export interface CustomerContactResponseDto {
    /**
     * 
     * @type {number}
     * @memberof CustomerContactResponseDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerContactResponseDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactResponseDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactResponseDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactResponseDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactResponseDto
     */
    jobTitle?: string;
}

/**
 * Check if a given object implements the CustomerContactResponseDto interface.
 */
export function instanceOfCustomerContactResponseDto(value: object): value is CustomerContactResponseDto {
    return true;
}

export function CustomerContactResponseDtoFromJSON(json: any): CustomerContactResponseDto {
    return CustomerContactResponseDtoFromJSONTyped(json, false);
}

export function CustomerContactResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerContactResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
    };
}

export function CustomerContactResponseDtoToJSON(json: any): CustomerContactResponseDto {
    return CustomerContactResponseDtoToJSONTyped(json, false);
}

export function CustomerContactResponseDtoToJSONTyped(value?: CustomerContactResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'jobTitle': value['jobTitle'],
    };
}

