/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerContactCreateDto
 */
export interface CustomerContactCreateDto {
    /**
     * 
     * @type {string}
     * @memberof CustomerContactCreateDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactCreateDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactCreateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerContactCreateDto
     */
    jobTitle?: string;
}

/**
 * Check if a given object implements the CustomerContactCreateDto interface.
 */
export function instanceOfCustomerContactCreateDto(value: object): value is CustomerContactCreateDto {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CustomerContactCreateDtoFromJSON(json: any): CustomerContactCreateDto {
    return CustomerContactCreateDtoFromJSONTyped(json, false);
}

export function CustomerContactCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerContactCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
    };
}

export function CustomerContactCreateDtoToJSON(json: any): CustomerContactCreateDto {
    return CustomerContactCreateDtoToJSONTyped(json, false);
}

export function CustomerContactCreateDtoToJSONTyped(value?: CustomerContactCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'jobTitle': value['jobTitle'],
    };
}

