/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressUpdateDto } from './AddressUpdateDto';
import {
    AddressUpdateDtoFromJSON,
    AddressUpdateDtoFromJSONTyped,
    AddressUpdateDtoToJSON,
    AddressUpdateDtoToJSONTyped,
} from './AddressUpdateDto';

/**
 * 
 * @export
 * @interface IndividualCustomerUpdateDto
 */
export interface IndividualCustomerUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerUpdateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerUpdateDto
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerUpdateDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerUpdateDto
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof IndividualCustomerUpdateDto
     */
    birthDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerUpdateDto
     */
    birthPlace?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerUpdateDto
     */
    nationality?: string;
    /**
     * 
     * @type {AddressUpdateDto}
     * @memberof IndividualCustomerUpdateDto
     */
    billingAddress?: AddressUpdateDto;
}

/**
 * Check if a given object implements the IndividualCustomerUpdateDto interface.
 */
export function instanceOfIndividualCustomerUpdateDto(value: object): value is IndividualCustomerUpdateDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function IndividualCustomerUpdateDtoFromJSON(json: any): IndividualCustomerUpdateDto {
    return IndividualCustomerUpdateDtoFromJSONTyped(json, false);
}

export function IndividualCustomerUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualCustomerUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'birthPlace': json['birthPlace'] == null ? undefined : json['birthPlace'],
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'billingAddress': json['billingAddress'] == null ? undefined : AddressUpdateDtoFromJSON(json['billingAddress']),
    };
}

export function IndividualCustomerUpdateDtoToJSON(json: any): IndividualCustomerUpdateDto {
    return IndividualCustomerUpdateDtoToJSONTyped(json, false);
}

export function IndividualCustomerUpdateDtoToJSONTyped(value?: IndividualCustomerUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'birthDate': value['birthDate'] == null ? value['birthDate'] : value['birthDate'].toISOString().substring(0,10),
        'birthPlace': value['birthPlace'],
        'nationality': value['nationality'],
        'billingAddress': AddressUpdateDtoToJSON(value['billingAddress']),
    };
}

