/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressResponseDto } from './AddressResponseDto';
import {
    AddressResponseDtoFromJSON,
    AddressResponseDtoFromJSONTyped,
    AddressResponseDtoToJSON,
    AddressResponseDtoToJSONTyped,
} from './AddressResponseDto';

/**
 * 
 * @export
 * @interface IndividualCustomerResponseDto
 */
export interface IndividualCustomerResponseDto {
    /**
     * 
     * @type {number}
     * @memberof IndividualCustomerResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerResponseDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerResponseDto
     */
    phoneNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof IndividualCustomerResponseDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerResponseDto
     */
    customerType?: IndividualCustomerResponseDtoCustomerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerResponseDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerResponseDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerResponseDto
     */
    fiscalCode?: string;
    /**
     * 
     * @type {Date}
     * @memberof IndividualCustomerResponseDto
     */
    birthDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerResponseDto
     */
    birthPlace?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerResponseDto
     */
    nationality?: string;
    /**
     * 
     * @type {AddressResponseDto}
     * @memberof IndividualCustomerResponseDto
     */
    billingAddress?: AddressResponseDto;
}


/**
 * @export
 */
export const IndividualCustomerResponseDtoCustomerTypeEnum = {
    Individual: 'INDIVIDUAL',
    Business: 'BUSINESS'
} as const;
export type IndividualCustomerResponseDtoCustomerTypeEnum = typeof IndividualCustomerResponseDtoCustomerTypeEnum[keyof typeof IndividualCustomerResponseDtoCustomerTypeEnum];


/**
 * Check if a given object implements the IndividualCustomerResponseDto interface.
 */
export function instanceOfIndividualCustomerResponseDto(value: object): value is IndividualCustomerResponseDto {
    return true;
}

export function IndividualCustomerResponseDtoFromJSON(json: any): IndividualCustomerResponseDto {
    return IndividualCustomerResponseDtoFromJSONTyped(json, false);
}

export function IndividualCustomerResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualCustomerResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'customerType': json['customerType'] == null ? undefined : json['customerType'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'fiscalCode': json['fiscalCode'] == null ? undefined : json['fiscalCode'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'birthPlace': json['birthPlace'] == null ? undefined : json['birthPlace'],
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'billingAddress': json['billingAddress'] == null ? undefined : AddressResponseDtoFromJSON(json['billingAddress']),
    };
}

export function IndividualCustomerResponseDtoToJSON(json: any): IndividualCustomerResponseDto {
    return IndividualCustomerResponseDtoToJSONTyped(json, false);
}

export function IndividualCustomerResponseDtoToJSONTyped(value?: IndividualCustomerResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'userId': value['userId'],
        'customerType': value['customerType'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'fiscalCode': value['fiscalCode'],
        'birthDate': value['birthDate'] == null ? value['birthDate'] : value['birthDate'].toISOString().substring(0,10),
        'birthPlace': value['birthPlace'],
        'nationality': value['nationality'],
        'billingAddress': AddressResponseDtoToJSON(value['billingAddress']),
    };
}

