/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressCreateDto } from './AddressCreateDto';
import {
    AddressCreateDtoFromJSON,
    AddressCreateDtoFromJSONTyped,
    AddressCreateDtoToJSON,
    AddressCreateDtoToJSONTyped,
} from './AddressCreateDto';

/**
 * 
 * @export
 * @interface IndividualCustomerCreateDto
 */
export interface IndividualCustomerCreateDto {
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerCreateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerCreateDto
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerCreateDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerCreateDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerCreateDto
     */
    fiscalCode: string;
    /**
     * 
     * @type {Date}
     * @memberof IndividualCustomerCreateDto
     */
    birthDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerCreateDto
     */
    birthPlace?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualCustomerCreateDto
     */
    nationality?: string;
    /**
     * 
     * @type {AddressCreateDto}
     * @memberof IndividualCustomerCreateDto
     */
    billingAddress: AddressCreateDto;
}

/**
 * Check if a given object implements the IndividualCustomerCreateDto interface.
 */
export function instanceOfIndividualCustomerCreateDto(value: object): value is IndividualCustomerCreateDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('fiscalCode' in value) || value['fiscalCode'] === undefined) return false;
    if (!('billingAddress' in value) || value['billingAddress'] === undefined) return false;
    return true;
}

export function IndividualCustomerCreateDtoFromJSON(json: any): IndividualCustomerCreateDto {
    return IndividualCustomerCreateDtoFromJSONTyped(json, false);
}

export function IndividualCustomerCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualCustomerCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'fiscalCode': json['fiscalCode'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'birthPlace': json['birthPlace'] == null ? undefined : json['birthPlace'],
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'billingAddress': AddressCreateDtoFromJSON(json['billingAddress']),
    };
}

export function IndividualCustomerCreateDtoToJSON(json: any): IndividualCustomerCreateDto {
    return IndividualCustomerCreateDtoToJSONTyped(json, false);
}

export function IndividualCustomerCreateDtoToJSONTyped(value?: IndividualCustomerCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'fiscalCode': value['fiscalCode'],
        'birthDate': value['birthDate'] == null ? value['birthDate'] : value['birthDate'].toISOString().substring(0,10),
        'birthPlace': value['birthPlace'],
        'nationality': value['nationality'],
        'billingAddress': AddressCreateDtoToJSON(value['billingAddress']),
    };
}

