/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { CustomerResponseDto } from './CustomerResponseDto';
import {
    CustomerResponseDtoFromJSON,
    CustomerResponseDtoFromJSONTyped,
    CustomerResponseDtoToJSON,
    CustomerResponseDtoToJSONTyped,
} from './CustomerResponseDto';

/**
 * 
 * @export
 * @interface PageResponseCustomerResponseDto
 */
export interface PageResponseCustomerResponseDto {
    /**
     * 
     * @type {Array<CustomerResponseDto>}
     * @memberof PageResponseCustomerResponseDto
     */
    content?: Array<CustomerResponseDto>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PageResponseCustomerResponseDto
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PageResponseCustomerResponseDto interface.
 */
export function instanceOfPageResponseCustomerResponseDto(value: object): value is PageResponseCustomerResponseDto {
    return true;
}

export function PageResponseCustomerResponseDtoFromJSON(json: any): PageResponseCustomerResponseDto {
    return PageResponseCustomerResponseDtoFromJSONTyped(json, false);
}

export function PageResponseCustomerResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseCustomerResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(CustomerResponseDtoFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PageResponseCustomerResponseDtoToJSON(json: any): PageResponseCustomerResponseDto {
    return PageResponseCustomerResponseDtoToJSONTyped(json, false);
}

export function PageResponseCustomerResponseDtoToJSONTyped(value?: PageResponseCustomerResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(CustomerResponseDtoToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

