/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PageResponsePermissionResponseDto,
  Pageable,
} from '../models/index';
import {
    PageResponsePermissionResponseDtoFromJSON,
    PageResponsePermissionResponseDtoToJSON,
    PageableFromJSON,
    PageableToJSON,
} from '../models/index';

export interface GetAllPermissionsRequest {
    pageable: Pageable;
}

/**
 * 
 */
export class PermissionManagementApi extends runtime.BaseAPI {

    /**
     * Retrieve available permissions
     */
    async getAllPermissionsRaw(requestParameters: GetAllPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageResponsePermissionResponseDto>> {
        if (requestParameters['pageable'] == null) {
            throw new runtime.RequiredError(
                'pageable',
                'Required parameter "pageable" was null or undefined when calling getAllPermissions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageable'] != null) {
            queryParameters['pageable'] = requestParameters['pageable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", []);
        }


        let urlPath = `/api/v1/permissions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageResponsePermissionResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve available permissions
     */
    async getAllPermissions(requestParameters: GetAllPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageResponsePermissionResponseDto> {
        const response = await this.getAllPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
