/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { UserResponseDto } from './UserResponseDto';
import {
    UserResponseDtoFromJSON,
    UserResponseDtoFromJSONTyped,
    UserResponseDtoToJSON,
    UserResponseDtoToJSONTyped,
} from './UserResponseDto';

/**
 * 
 * @export
 * @interface PageResponseUserResponseDto
 */
export interface PageResponseUserResponseDto {
    /**
     * 
     * @type {Array<UserResponseDto>}
     * @memberof PageResponseUserResponseDto
     */
    content?: Array<UserResponseDto>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PageResponseUserResponseDto
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PageResponseUserResponseDto interface.
 */
export function instanceOfPageResponseUserResponseDto(value: object): value is PageResponseUserResponseDto {
    return true;
}

export function PageResponseUserResponseDtoFromJSON(json: any): PageResponseUserResponseDto {
    return PageResponseUserResponseDtoFromJSONTyped(json, false);
}

export function PageResponseUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UserResponseDtoFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PageResponseUserResponseDtoToJSON(json: any): PageResponseUserResponseDto {
    return PageResponseUserResponseDtoToJSONTyped(json, false);
}

export function PageResponseUserResponseDtoToJSONTyped(value?: PageResponseUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UserResponseDtoToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

