/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PermissionResponseDto } from './PermissionResponseDto';
import {
    PermissionResponseDtoFromJSON,
    PermissionResponseDtoFromJSONTyped,
    PermissionResponseDtoToJSON,
    PermissionResponseDtoToJSONTyped,
} from './PermissionResponseDto';

/**
 * 
 * @export
 * @interface PageResponsePermissionResponseDto
 */
export interface PageResponsePermissionResponseDto {
    /**
     * 
     * @type {Array<PermissionResponseDto>}
     * @memberof PageResponsePermissionResponseDto
     */
    content?: Array<PermissionResponseDto>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PageResponsePermissionResponseDto
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PageResponsePermissionResponseDto interface.
 */
export function instanceOfPageResponsePermissionResponseDto(value: object): value is PageResponsePermissionResponseDto {
    return true;
}

export function PageResponsePermissionResponseDtoFromJSON(json: any): PageResponsePermissionResponseDto {
    return PageResponsePermissionResponseDtoFromJSONTyped(json, false);
}

export function PageResponsePermissionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponsePermissionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PermissionResponseDtoFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PageResponsePermissionResponseDtoToJSON(json: any): PageResponsePermissionResponseDto {
    return PageResponsePermissionResponseDtoToJSONTyped(json, false);
}

export function PageResponsePermissionResponseDtoToJSONTyped(value?: PageResponsePermissionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PermissionResponseDtoToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

