/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleResponseDto } from './RoleResponseDto';
import {
    RoleResponseDtoFromJSON,
    RoleResponseDtoFromJSONTyped,
    RoleResponseDtoToJSON,
    RoleResponseDtoToJSONTyped,
} from './RoleResponseDto';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';

/**
 * 
 * @export
 * @interface PageResponseRoleResponseDto
 */
export interface PageResponseRoleResponseDto {
    /**
     * 
     * @type {Array<RoleResponseDto>}
     * @memberof PageResponseRoleResponseDto
     */
    content?: Array<RoleResponseDto>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PageResponseRoleResponseDto
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PageResponseRoleResponseDto interface.
 */
export function instanceOfPageResponseRoleResponseDto(value: object): value is PageResponseRoleResponseDto {
    return true;
}

export function PageResponseRoleResponseDtoFromJSON(json: any): PageResponseRoleResponseDto {
    return PageResponseRoleResponseDtoFromJSONTyped(json, false);
}

export function PageResponseRoleResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseRoleResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(RoleResponseDtoFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PageResponseRoleResponseDtoToJSON(json: any): PageResponseRoleResponseDto {
    return PageResponseRoleResponseDtoToJSONTyped(json, false);
}

export function PageResponseRoleResponseDtoToJSONTyped(value?: PageResponseRoleResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(RoleResponseDtoToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

