/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionResponseDto
 */
export interface PermissionResponseDto {
    /**
     * 
     * @type {number}
     * @memberof PermissionResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponseDto
     */
    authority?: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponseDto
     */
    description?: string;
}

/**
 * Check if a given object implements the PermissionResponseDto interface.
 */
export function instanceOfPermissionResponseDto(value: object): value is PermissionResponseDto {
    return true;
}

export function PermissionResponseDtoFromJSON(json: any): PermissionResponseDto {
    return PermissionResponseDtoFromJSONTyped(json, false);
}

export function PermissionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'authority': json['authority'] == null ? undefined : json['authority'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function PermissionResponseDtoToJSON(json: any): PermissionResponseDto {
    return PermissionResponseDtoToJSONTyped(json, false);
}

export function PermissionResponseDtoToJSONTyped(value?: PermissionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'authority': value['authority'],
        'description': value['description'],
    };
}

