/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionResponseDto } from './PermissionResponseDto';
import {
    PermissionResponseDtoFromJSON,
    PermissionResponseDtoFromJSONTyped,
    PermissionResponseDtoToJSON,
    PermissionResponseDtoToJSONTyped,
} from './PermissionResponseDto';

/**
 * 
 * @export
 * @interface RoleResponseDto
 */
export interface RoleResponseDto {
    /**
     * 
     * @type {number}
     * @memberof RoleResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleResponseDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleResponseDto
     */
    description?: string;
    /**
     * 
     * @type {Set<PermissionResponseDto>}
     * @memberof RoleResponseDto
     */
    permissions?: Set<PermissionResponseDto>;
}

/**
 * Check if a given object implements the RoleResponseDto interface.
 */
export function instanceOfRoleResponseDto(value: object): value is RoleResponseDto {
    return true;
}

export function RoleResponseDtoFromJSON(json: any): RoleResponseDto {
    return RoleResponseDtoFromJSONTyped(json, false);
}

export function RoleResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'permissions': json['permissions'] == null ? undefined : (new Set((json['permissions'] as Array<any>).map(PermissionResponseDtoFromJSON))),
    };
}

export function RoleResponseDtoToJSON(json: any): RoleResponseDto {
    return RoleResponseDtoToJSONTyped(json, false);
}

export function RoleResponseDtoToJSONTyped(value?: RoleResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'permissions': value['permissions'] == null ? undefined : (Array.from(value['permissions'] as Set<any>).map(PermissionResponseDtoToJSON)),
    };
}

