/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleCreateDto
 */
export interface RoleCreateDto {
    /**
     * 
     * @type {string}
     * @memberof RoleCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoleCreateDto
     */
    description?: string;
    /**
     * 
     * @type {Set<number>}
     * @memberof RoleCreateDto
     */
    permissions: Set<number>;
}

/**
 * Check if a given object implements the RoleCreateDto interface.
 */
export function instanceOfRoleCreateDto(value: object): value is RoleCreateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function RoleCreateDtoFromJSON(json: any): RoleCreateDto {
    return RoleCreateDtoFromJSONTyped(json, false);
}

export function RoleCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'permissions': new Set(json['permissions']),
    };
}

export function RoleCreateDtoToJSON(json: any): RoleCreateDto {
    return RoleCreateDtoToJSONTyped(json, false);
}

export function RoleCreateDtoToJSONTyped(value?: RoleCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'permissions': Array.from(value['permissions'] as Set<any>),
    };
}

