/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleUpdateDto
 */
export interface RoleUpdateDto {
    /**
     * 
     * @type {Set<number>}
     * @memberof RoleUpdateDto
     */
    permissions: Set<number>;
}

/**
 * Check if a given object implements the RoleUpdateDto interface.
 */
export function instanceOfRoleUpdateDto(value: object): value is RoleUpdateDto {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function RoleUpdateDtoFromJSON(json: any): RoleUpdateDto {
    return RoleUpdateDtoFromJSONTyped(json, false);
}

export function RoleUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': new Set(json['permissions']),
    };
}

export function RoleUpdateDtoToJSON(json: any): RoleUpdateDto {
    return RoleUpdateDtoToJSONTyped(json, false);
}

export function RoleUpdateDtoToJSONTyped(value?: RoleUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissions': Array.from(value['permissions'] as Set<any>),
    };
}

