/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateDto
 */
export interface UserUpdateDto {
    /**
     * 
     * @type {Set<number>}
     * @memberof UserUpdateDto
     */
    roles: Set<number>;
}

/**
 * Check if a given object implements the UserUpdateDto interface.
 */
export function instanceOfUserUpdateDto(value: object): value is UserUpdateDto {
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function UserUpdateDtoFromJSON(json: any): UserUpdateDto {
    return UserUpdateDtoFromJSONTyped(json, false);
}

export function UserUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'roles': new Set(json['roles']),
    };
}

export function UserUpdateDtoToJSON(json: any): UserUpdateDto {
    return UserUpdateDtoToJSONTyped(json, false);
}

export function UserUpdateDtoToJSONTyped(value?: UserUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roles': Array.from(value['roles'] as Set<any>),
    };
}

