/* tslint:disable */
/* eslint-disable */
/**
 * User Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleResponseDto } from './RoleResponseDto';
import {
    RoleResponseDtoFromJSON,
    RoleResponseDtoFromJSONTyped,
    RoleResponseDtoToJSON,
    RoleResponseDtoToJSONTyped,
} from './RoleResponseDto';

/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * 
     * @type {number}
     * @memberof UserResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    email?: string;
    /**
     * 
     * @type {Set<RoleResponseDto>}
     * @memberof UserResponseDto
     */
    roles?: Set<RoleResponseDto>;
}

/**
 * Check if a given object implements the UserResponseDto interface.
 */
export function instanceOfUserResponseDto(value: object): value is UserResponseDto {
    return true;
}

export function UserResponseDtoFromJSON(json: any): UserResponseDto {
    return UserResponseDtoFromJSONTyped(json, false);
}

export function UserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'roles': json['roles'] == null ? undefined : (new Set((json['roles'] as Array<any>).map(RoleResponseDtoFromJSON))),
    };
}

export function UserResponseDtoToJSON(json: any): UserResponseDto {
    return UserResponseDtoToJSONTyped(json, false);
}

export function UserResponseDtoToJSONTyped(value?: UserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'roles': value['roles'] == null ? undefined : (Array.from(value['roles'] as Set<any>).map(RoleResponseDtoToJSON)),
    };
}

